### PR TITLE
typings support

### PR DESCRIPTION
**Pull request by likerRr**
Hi!

Just noticed that you've committed [typings support](https://github.com/cyraxx/node-pogo-protos/commit/1e65b475fb102a0a78257514e5713ed74f293312). I've been working on ts support for few last days and I wanted to make pull request today, but you've beaten me :) Nice that you did it, but unfortunately this automatic generated file has some issues in it. 

The meaning of "module" in typescript is no longer used as it's done in [Proto2TypeScript](https://github.com/SINTEF-9012/Proto2TypeScript). The "namespace"-way is [prefered now](https://www.typescriptlang.org/docs/handbook/modules.html).

Second issues are praised auto completeion and go-to declaration benefits. Look how it works with Proto2TypeScript in WebStorm:

7205e-clip-59kb

> At the picture there is no auto completeion after the "Messages."

e8bec-clip-78kb

> Go to declaration feature goes crazy

And the last what I've noticed it doesn't allow you to use your module with ES6 module syntax:
`import * as POGOProtos from 'node-pogo-protos';`
## Solution

I made a generator that produced attached pogo-protos.d.ts file. You can notice the advantages over the Proto2TypeScript:
1. The declaration file doesn't declare any external module.
2. All messages are grouped by the namespace that allows better code completion and go to declaration features.
   6dcce-clip-76kb
   > better auto complete

47fc3-clip-30kb

> Go to declaration moves you to class's declaration
1. You can use ES6 module syntax :+1: 

I made it special for the `node-pogo-protos` so if you like it, I will update generator package and will push it at github and provide you with instruction how to generate such files.

### CODE REVIEW

**Comment by cyraxx** [comment]
I don't know much about TypeScript but I'll take your word for it :smiley:

So please do include your generator. It needs to be possible to quickly update the typings whenever there's a proto update, so a fully automated way is preferred.

**Comment by likerRr** [comment]
Glad to hear it! Will do it in few days :)

**Comment by likerRr** [comment]
@cyraxx Hi! 

I just pushed [a module](https://github.com/likerRr/npp2ts) that is able to generate typescript definitions from .json protos model. For now it doesn't have any specific options and I hope you won't face any difficulties with it. 

I also updated the PR with the corresponding changes. I don't recommend you to remove question marks from .d.t.s file, because it marks properties as optional and if you removed them, all the fields will be required.

**Comment by cyraxx** [comment]
Thanks for the module! A few notes:
- The `npp2ts` CLI script seems to have an issue with line endings - when I run it, I get `env: node\r: No such file or directory`. After manually converting the line endings from DOS to UNIX it worked.
- Looks like you use the data type `string` for all longs. When you get the decoded messages back from protobuf.js they are actually Long.js instances (which is why I referenced `long.d.ts`). Similar issue for buffers I believe.
- Removing the questions marks was something that @Alph44rchitect added who supplied the original typings. I'm not sure what his reasoning was, maybe he can chime in.

**Comment by likerRr** [comment]
Thank for the notes!
- I will check it once again, but I tested it on Win10 inside their new bash with ubuntu support and haven't experienced such issue
- [Here is](https://github.com/likerRr/npp2ts/blob/master/src/proto-type-resolver.ts) how the types are resolved. Data type `string` resolves for strings only. Could you please clarify which of the types should be resolved as `Long`s?

I didn't include `bytebuffer.d.ts` because I wasn't sure about naming collision in case when developer has already installed these typings. But I can include `long.d.ts` and `buffer.d.ts` through the [typings](https://github.com/likerRr/npp2ts/blob/master/typings.json).

Sorry if I explain unclear :)

**Comment by Alph44rchitect** [comment]
First I have to say I never created typings before so I have not much experience with that. But I wanted autocompletion instead of everytime looking into the wiki or the protos and it looked like nobody else is doing that. So I gave it a try.
- I removed the question marks because it looked like proto2ts had set them for every attribute. And for many of them that made no sense for me. My main focus for providing this typings was for the pogobuf typings which only use the response messages and there I think the optional parameter makes no sense or? Because of that I think I haven't thought longer about this.

But I also have a few questions:
- Does the getter and setter methods makes sense? Are they implemented via protobuf.js or something else or do they working there own? Why not just access via attribute in this case?
- Same question for the ProtobufMessage. Never worked with protobuf.js so are these functions for example: `encode64()` provided by them or something else or are they senseless? For me as enduser which only wants to know which attributes the response has, it's looking a bit like overhead. And they are not existing anymore in this case or? [protobuf.d.ts](https://github.com/cyraxx/pogobuf/blob/master/pogobuf.d.ts) Or I'm using them wrong? overheadv2

To your question:
- According to [proto2typescript](https://github.com/SINTEF-9012/Proto2TypeScript/blob/master/command.js#L44) I think every 64 Bit type should be Long.

**Comment by likerRr** [comment]
Thx for the answer, @Alph44rchitect .

`Does the getter and setter methods makes sense?` They do. Actually there are three ways of getting/setting properties. The screenshot below was taken in debug mode, so it's what `protobufjs` returns when a message is instantiated:


`Why not just access via attribute in this case?` Not sure is there any advantages of accessing by property or be getters.

`are these functions for example: encode64() provided by them` It's true, you can manually debug the message fromt this example:

``` javascript
const POGOProtos = require('node-pogo-protos');

var myMessage = new POGOProtos.Networking.Requests.Messages.RecycleInventoryItemMessage({
  item_id: POGOProtos.Inventory.Item.ItemId.ITEM_POTION,
  count: 50
});
```

Or just look at the picture above, it also shows these methods.

`For me as enduser which only wants to know which attributes the response has` Each attribute has a type, and in your case `map_cells` is the `array` of `MapCell` message objects. Since they are message objects, they have all the methods available for message instance.

It's not an overhead when you write the code on pure typescript. If you try to call a method that doesn't exist typescript won't compile such file. That why I added declaration of static and instance methods of protobuf message.

`And they are not existing anymore in this case or?` They exists. I run little test:

``` javascript
var myMessage = new POGOProtos.Networking.Responses.GetMapObjectsResponse({
  map_cells: [new POGOProtos.Map.MapCell({})],
  status: 50
});

var encoded = myMessage.encode();
var decodedAgain = POGOProtos.Networking.Responses.GetMapObjectsResponse.decode(encoded);
```

And here is what `decodedAgain.map_cells[0]` is:


`I removed the question marks because it looked like proto2ts had set them for every attribute` great news! `npp2ts` sets question mark only if field's type is optional :)

**Comment by likerRr** [comment]
@cyraxx @Alph44rchitect I updated both `npp2ts` and pogo-protos typings generation.
- `The npp2ts CLI script seems to have an issue with line endings` - set LF for all `js` files
- `Looks like you use the data type string for all longs` - `Long`s are used as replacement for 64bit types
- added references to `Long.d.ts` and `ByteBuffer.d.ts` at the top of generated definitions

Please test and share your opinion

**Comment by cyraxx** [comment]
Looks good to me!

@Alph44rchitect, can you give these a spin? Do you have anything else to add?

**Comment by Alph44rchitect** [comment]
Yes @cyraxx  I think I can agree with that answers. :P Thank you @likerRr.

There is only one problem now when I try to import via `import * as POGOProtos from 'node-pogo-protos';`

Then I get the following error:
`error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.`

**Comment by likerRr** [comment]
@cyraxx @Alph44rchitect thank you guys.

@Alph44rchitect this is quite tricky case...

I experimented whole the morning and here what I can resume:
1. We can't combine definitions by adding triple slash references to them
2. If we want to deliver definitions within `node-pogo-protos` then we can't combine it with `long` and `bytebuffer`. Because of p1.

There is two solutions:
- deliver definitions without `long.d.ts` and `bytebuffer.d.ts`. They are not dependencies of `pogo-protos` and should be installed manually by the user who installs `node-pogo-protos`. 
- exclude definitions from the module and add them to [dt repo](https://github.com/DefinitelyTyped/DefinitelyTyped). This way anyone will be able set up definitions when he needs them.

I prefer the first variant and my latest commit contains changes for it. Also I created [test repo](https://github.com/likerRr/test-npp) to show how developer will work with this.

Sorry for complexity, but I'm sure we are on the right way :) 

What do you think?

**Comment by Alph44rchitect** [comment]
@likerRr is it maybe also possible to create a typings.json that will resolve the dependencies on installing the package? I'm not home at the moment otherwise I would test that for you.

If not then I would also prefere the first solution you did.

**Comment by likerRr** [comment]
@Alph44rchitect sure, and it's already done in test app that I've mentioned above. You just have to describe  postinstall script in package.json. Is it what you need?

**Comment by Alph44rchitect** [comment]
@likerRr sorry I think I was not precise enough. I was asking if it's possible to add a typings.json to node-pogo-protos package which gets resolved when installing it via `npm install node-pogo-protos` into my own project.

**Comment by likerRr** [comment]
As far as I know dependencies can't affect your project. As it turned out it's not easy to add typescript definitions to project when it depends on other definitions (like long and bytebuffer).

**Comment by Alph44rchitect** [comment]
Okay then we have to go with your solution. From my side everything is clarified now @cyraxx. Thanks for your improvments @likerRr.

**Comment by likerRr** [comment]
@Alph44rchitect anytime! :)

@cyraxx I think we should also put few strings in readme about how to work with `node-pogo-protos` in typescript, what do you think?

**Comment by cyraxx** [comment]
@likerRr Thanks for your work! And sure, we can put some stuff in README, do you have a template?

**Pull request merged**
