### PR TITLE
Update node modules

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by Lord-Haji** [comment]
@cyraxx https://github.com/likerRr/npp2ts this has improved a lot too. I am sure it will give a better performance now

**Comment by niicojs** [comment]
npp2ts should not be necessary as protobufjs 6 does it out of the box

**Comment by Lord-Haji** [comment]
@nicoschmitt I thought npp2ts is used to generate typings isnt ?

**Comment by niicojs** [comment]
Yes it is. But protobufs 6 can also do it now.

**Comment by cyraxx** [comment]
I think we can't just switch to protobufjs 6 as it comes with some API changes that might break other modules using node-pogo-protos. See also #11.

**Comment by niicojs** [comment]
I did a PR with protobufjs 6. It indeed break stuff... I did the change on my pogobuf fork.

**Pull request closed without merging**
