### PR TITLE
[Major Update] Switch to protobufjs 6

### PR DESCRIPTION
**Pull request by niicojs**
Switch to protobufjs 6.
The thing is protobufjs api changed a lot, so this is a breaking change for all modules using it.
This has a be a major update (and probably a dedicated branch even).

Benefits:
 - static compiled js and .d.ts directly using protobufjs
 - performance
 - no more hack for packed field

### CODE REVIEW

**Comment by cyraxx** [comment]
I've changed `UPDATING.md` to use npm scripts, @nicoschmitt could you confirm that they work on Windows?

**Comment by niicojs** [comment]
@cyraxx I've tested and it works fine thanks.
I've just added a way to load from disk if needed (it's helpful when I debug protos for example).

**Comment by cyraxx** [comment]
## :warning: THIS REPOSITORY IS NO LONGER UNDER ACTIVE MAINTENANCE. FOR FURTHER DEVELOPMENT PLEASE SEE THE [POGOSANDBOX FORK](https://github.com/pogosandbox/pogobuf). :warning:

**Comment by cyraxx** [comment]
Closing all issues as this repository is no longer being maintained. See README for further information.

**Pull request closed without merging**
