### PR TITLE
Update from latest + Bug fix on packed repeating

### PR DESCRIPTION
**Pull request by niicojs**
I also code a little script to convert AeonLucid proto to this format (that's why files are named differently here). 
I can share if of any interest.

### CODE REVIEW

**Comment by cyraxx** [comment]
I'm not sure what you did here.

I just checked by updating my local copy to AeonLucid's latest protos and the only thing that changed between v2.4.0 (which is the current version in node-pogo-protos) and v2.4.2 (latest) is a single comment change. To me it looks like the only thing that changed in this PR is that everything is split into lots of individual .proto files.

As for the bug fix, I'm a little confused why this is suddenly necessary when it worked before. Was there a change in protobuf.js recently? Were you getting errors without the fix?

**Comment by niicojs** [comment]
Fair question :)
I was looking for a proto that did not exist in your repo, so I ended up coding a tool to automate converting format from Aeon to yours. At the end, the proto I was looking for did not exist either in Aeon...
I don't know if you update manually or not, with this PR it looks more like the file in Aeon's. That's really up to you.

About the bugfix, it happens only in repeating field inside message within a message, for example in signature. And I guess there isn't to much people working with signature.

**Comment by cyraxx** [comment]
Which proto is the one that was missing? There should be no difference between AeonLucid's current protos and the ones in node-pogo-protos.

Updating the protos is actually pretty easy but looks like I've never actually documented it. I'll go ahead and add some documentation.

**Comment by niicojs** [comment]
it's GET_STORE_ITEMS_REQUEST, as I said it's not in AeonLucid repo either but I just thought it did :)

**Comment by cyraxx** [comment]
Whoops, I misread that, sorry.

The system we have in place for updating the protos is pretty solid (I'll add documentation in a minute) so if it's fine with you I'd like to close this PR and you could open a second one with only the bugfix.

**Comment by niicojs** [comment]
Sure, make sense.

**Pull request closed without merging**
